properties:
  name: joohyun
  number: 0
  wishlist: PS5

spring:
  application:
    name: ${properties.name}
  profiles:
    active: default
  cloud:
    config:
      enabled: false
#  config:
#    import: "configserver:http://sw-edu-config.211-34-231-82.nip.io"

eureka:
  client:
    serviceUrl:
      defaultZone: http://sw-edu-eureka.211-34-231-82.nip.io/eureka/
    enabled: false
  instance:
    instance-id: 1
    appname: ${properties.name}
    prefer-ip-address: true
    ip-address: 192.168.2.3

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,metrics,env,info,refresh
  endpoint:
    health:
      enabled: true
      show-details: always
    refresh:
      enabled: true
  info:
    defaults:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  health:
    defaults:
      enabled: false
