properties:
  name: joohyun
  number: 0
  wishlist: PS5

spring:
  application:
    name: ${properties.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://sw-edu-eureka.211-34-231-82.nip.io/eureka/
  instance:
    instance-id: 1
    appname: ${properties.name}
    prefer-ip-address: true
    ip-address: 192.168.2.3

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,metrics,env,info
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    defaults:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
  health:
    defaults:
      enabled: false
